spring:
  thymeleaf:
    cache: 'false'
    mode: html
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  mvc:
    locale: pt_BR
    locale-resolver: fixed
    favicon:
      enabled: true
  h2.console:
    enabled: true
    path: /db
  datasource:
    url: jdbc:h2:~/dev;DB_CLOSE_ON_EXIT=TRUE
    platform: h2
  